# Generated by Django 3.2.4 on 2021-06-19 16:11

from django.db import migrations, models
import django.db.models.deletion
import projectmanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('EmployeeID', models.CharField(default=projectmanager.models.EmployeeIDGenerator, max_length=100, unique=True)),
                ('EMail', models.EmailField(max_length=254, unique=True)),
                ('Contact', models.IntegerField()),
                ('Manager_Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_and_Date_Created', models.DateField(auto_now_add=True)),
                ('Project_Title', models.CharField(max_length=100)),
                ('Project_Description', models.TextField()),
                ('Project_Link', models.URLField(unique=True)),
                ('Project_Gravatar', models.URLField()),
                ('Project_Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time_Created', models.TimeField(auto_now_add=True)),
                ('Task', models.TextField()),
                ('Subtasks', models.TextField()),
                ('Task_Reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanager.project')),
            ],
        ),
    ]
